/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: NateSquared (https://sketchfab.com/NateSquared)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/game-case-b9f59fa49f4c465c94ec262b21898d54
Title: Game Case
*/

import { Mesh, MeshStandardMaterial } from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>;
  materials: Record<string, MeshStandardMaterial>;
};

export function Game_Case_Model(props: any) {
  const { nodes, materials } = useGLTF(
    "/3D_Models/game_case.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.BoxArt_Rounded}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.Case}
        />
      </group>  
    </group>
  );
}

useGLTF.preload("/3D_Models/game_case.glb");
